# ~/.config/alacritty/alacritty.toml
[font]
normal = { family = "AdwaitaMono Nerd Font Mono", style = "Regular" }
size = 12.0

[window]
opacity = 0.7
padding = { x = 5, y = 5 }

[scrolling]
history = 10000
